export {
    EstadoUsuario,
    TipoRuta,
    EstadoRuta,
    FrecuenciaHorario,
    VigenciaHorario,
    EstadoHorario,
    EstadoBoleto,
    MetodoPago,
    EstadoVenta,
    TipoServicio,
    EstadoAutobus,
    TipoMantenimiento,
    EstadoConductor,
    EstadoAnden,
    EstadoAsignacion,
    EstadoEquipaje,
} from '@prisma/client'
